---
- name: Install rails dependencies
  yum: name={{ item }} state=present
  with_items:
    - sqlite-devel
    - mysql-devel
    - postgresql-devel

- name: Install rails
  gem: name=rails version={{ rails_version }} user_install=no state=present
